### PR TITLE
Add Simple Baselines and Metrics

### LINKED ISSUE #1: Add Metrics and Simple Baselines
We should have standard metrics and very simple baselines for use in training our models. 

Baseline Models:
- [x] All 0's
- [x] All max capacity
- [x] Last-value persistence
- [ ] Last-day persistence (copy the last day as the next days forecast)
- [ ] PV Live intraday

Metrics:
- [x] NMAE
- [x] Error during morning, afternoon, and evening
- [x] Error across different time horizons
- [x] Error in different Winter, Spring, Summer, Fall
- [x] RMSE
- [x] MAE
- [x] Count of errors larger than 1 and 2 GigaWatts option
- [x] Option to keep night time data, or remove it ( defined by sun angle)
- [ ] % of errors above 1.65 sigma, with sigma being the standard deviation of the outturn

### PR DESCRIPTION
**Pull request by jacobbieker**
# Pull Request

## Description

This PR adds very simple baseline models and metrics from #1

Fixes #1 

## How Has This Been Tested?

Unit tests

- [x] Yes

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/nowcasting/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by jacobbieker** [comment]
I've added everything other than the PVLive, sigma, and last day persistence to the v1 PR. Will add those other ones later, but these were the most simple ones to add and I think give a good, basic first version.

**Comment by jacobbieker** [comment]
Also to note, the tests are passing CodeCov is failing to upload

**Review by peterdudfield — COMMENTED** [review]
This looks really good. Great to have all these available. 

Could you do a little example in the `readme.md`,  this will help show people how to use it. 

and probably a different issue, could you do a load from csv method, run all metrics, then save results to csv. This will be useful to evaluate models

**Comment by jacobbieker** [comment]
> This looks really good. Great to have all these available.
> 
> Could you do a little example in the `readme.md`, this will help show people how to use it.
> 
> and probably a different issue, could you do a load from csv method, run all metrics, then save results to csv. This will be useful to evaluate models

Is there a standard format for the CSV model outputs that I should try to use for the inputs?

**Comment by peterdudfield** [comment]
> > This looks really good. Great to have all these available.
> > Could you do a little example in the `readme.md`, this will help show people how to use it.
> > and probably a different issue, could you do a load from csv method, run all metrics, then save results to csv. This will be useful to evaluate models
> 
> Is there a standard format for the CSV model outputs that I should try to use for the inputs?

Simliar to this - https://github.com/openclimatefix/nowcasting_utils/blob/main/nowcasting_utils/metrics/evaluation.py

**Comment by jacobbieker** [comment]
> > > This looks really good. Great to have all these available.
> > > Could you do a little example in the `readme.md`, this will help show people how to use it.
> > > and probably a different issue, could you do a load from csv method, run all metrics, then save results to csv. This will be useful to evaluate models
> > 
> > 
> > Is there a standard format for the CSV model outputs that I should try to use for the inputs?
> 
> Simliar to this - https://github.com/openclimatefix/nowcasting_utils/blob/main/nowcasting_utils/metrics/evaluation.py

Okay, thanks! I've copied over and modified it a bit to compute the metrics based off a pandas dataframe. This is a bit more general than the GSP specific one there, so requires a few more inputs in the input dataframe. For the outputs, I'd probably still leave it as a dictionary for now, there are a lot of summary and per-timestep metrics computed, and then more downstream code can choose what to plot/save out.

**Comment by jacobbieker** [comment]
I think for now, I'll just merge this and a v2 can have the write out to CSV. The current evaluation on the test example (2 IDs, 5 forecasts total, 3 simple baseline forecasts) is 600 metrics. So quite a lot to work with already.

**Pull request merged**
